const novelCategoriesOptions = [
    { value: "1", label: "Action" },
    { value: "49", label: "Adapted to Anime" },
    { value: "51", label: "Adapted to Drama CD" },
    { value: "50", label: "Adapted to Manga" },
    { value: "28", label: "Adult" },
    { value: "2", label: "Adventure" },
    { value: "52", label: "Age Gap" },
    { value: "60", label: "Boys Love" },
    { value: "54", label: "Character Growth" },
    { value: "39", label: "Chinese Novel" },
    { value: "3", label: "Comedy" },
    { value: "43", label: "Cooking" },
    { value: "56", label: "Different Social Status" },
    { value: "4", label: "Drama" },
    { value: "5", label: "Ecchi" },
    { value: "40", label: "English Novel" },
    { value: "6", label: "Fantasy" },
    { value: "59", label: "Female Protagonist" },
    { value: "45", label: "Game" },
    { value: "7", label: "Gender Bender" },
    { value: "8", label: "Harem" },
    { value: "35", label: "Historical" },
    { value: "9", label: "Horror" },
    { value: "10", label: "Incest" },
    { value: "30", label: "Isekai" },
    { value: "33", label: "Josei" },
    { value: "34", label: "Korean Novel" },
    { value: "44", label: "Magic" },
    { value: "37", label: "Martial Arts" },
    { value: "27", label: "Mature" },
    { value: "11", label: "Mecha" },
    { value: "36", label: "Military" },
    { value: "58", label: "Misunderstanding" },
    { value: "12", label: "Mystery" },
    { value: "32", label: "Netorare" },
    { value: "38", label: "One shot" },
    { value: "46", label: "Otome Game" },
    { value: "61", label: "Parody" },
    { value: "23", label: "Psychological" },
    { value: "47", label: "Reverse Harem" },
    { value: "22", label: "Romance" },
    { value: "13", label: "School Life" },
    { value: "14", label: "Science Fiction" },
    { value: "31", label: "Seinen" },
    { value: "15", label: "Shoujo" },
    { value: "16", label: "Shoujo ai" },
    { value: "26", label: "Shounen" },
    { value: "17", label: "Shounen ai" },
    { value: "18", label: "Slice of Life" },
    { value: "55", label: "Slow Life" },
    { value: "19", label: "Sports" },
    { value: "24", label: "Super Power" },
    { value: "20", label: "Supernatural" },
    { value: "25", label: "Suspense" },
    { value: "21", label: "Tragedy" },
    { value: "53", label: "Wars" },
    { value: "29", label: "Web Novel" },
    { value: "57", label: "Workplace" },
    { value: "48", label: "Yuri" },
]

export default novelCategoriesOptions;